# File: .github/workflows/selenium-testng-manual.yml
name: Selenium TestNG Manual Run

on:
  workflow_dispatch:   # Enables manual triggering from the Actions tab
    inputs:
      headlessOption:
        description: "Run test with headless option"
        required: true
        default: "yes"
        type: choice
        options:
          - yes
          - no

jobs:
  test:
    name: Run Selenium TestNG Tests
    runs-on: ubuntu-latest

    env:
      HEAD_LESS: ${{ github.event.inputs.headlessOption }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Install Chrome browser
        uses: browser-actions/setup-chrome@latest

      - name: Display Chrome version
        run: chrome --version

      - name: Run TestNG suite
        run: mvn clean test -DsuiteXmlFile=Testng/testng.xml -DheadlessEnable=${HEAD_LESS}

      - name: Upload Extent Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ExtentReport
          path: target/extent-report/Report_*.html