# File: .github/workflows/selenium-testng-manual.yml
name: Selenium TestNG Manual Run

on:
  workflow_dispatch:   # Enables manual triggering from the Actions tab

jobs:
  test:
    name: Run Selenium TestNG Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Install Chrome browser
        uses: browser-actions/setup-chrome@latest

      - name: Display Chrome version
        run: chrome --version

      - name: Run TestNG suite
        run: mvn clean test -DsuiteXmlFile=testng.xml
